### ISSUE TITLE
How is fastCSV licensed?

### ISSUE THREAD

**Issue by joelverhagen** [mgholam/fastCSV#11]
I am interested in using fastCSV in an open source project due to it's excellent performance but I am unsure of the license terms.

From the project URL on the package page, I see that this GitHub repository may be licensed under Code Project Open License (CPOL), but I'm not sure since the CPOL information is not even on GitHub. Would it be possible for you to release it under a more common license like MIT or Apache-2.0?

This is all I know about CPOL:
https://en.wikipedia.org/wiki/Code_Project_Open_License#Status_as_an_open-source_license

Also, do you think you could include the license in the next package version so that it appears on nuget.org?
https://www.nuget.org/packages/mgholam.fastCSV/

There is a document on how to do that here:
https://docs.microsoft.com/en-us/nuget/reference/msbuild-targets#packing-a-license-expression-or-a-license-file

**Comment by joelverhagen** [comment]
One convention many repos follow it to put the license in the root of the repo as "LICENSE.txt" and update the GitHub repository metadata to state the license.

**Comment by mgholam** [comment]
I've added a MIT license.

**Comment by mgholam** [comment]
Also check out my other repo which goes well with `fastCSV` : [https://github.com/mgholam/noDB](https://github.com/mgholam/noDB)

**Comment by joelverhagen** [comment]
Wonderful! Thanks!
