### ISSUE TITLE
Unknown/variable column count

### ISSUE THREAD

**Issue by MarkPflug** [mgholam/fastCSV#14]
Hello Mehdi,

I'm trying to add your library to some .NET CSV benchmarks that I'm collecting, and while I've made it work, I wonder if there isn't a faster way to do what I'm trying to do.

The biggest issues that I see is that I can't figure out how to handle a variable number of columns. My specific test dataset is the [Johns Hopkins University covid data set](https://github.com/CSSEGISandData/COVID-19/blob/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_confirmed_US.csv), which is updated daily and adds a new *column* ever day. A bit unusual, perhaps, but I can't figure out an elegant way to process this CSV with your library.

My benchmark project is [CSVBenchmarks](https://github.com/MarkPflug/CsvBenchmarks).

The benchmark for your library is here: [mgholam.fastCSV](https://github.com/MarkPflug/CsvBenchmarks/blob/bc2b4452f57a11bbd73e4329f0c7442ef5c46838/source/CsvBenchmark/CsvReaderBenchmarks.cs#L353-L389)

The comments in the code segment above highlight a few of the issues. I'd happily accept a PR with a better solution if you can provide one.

Thanks.

By the way, I became aware of your project via @joelverhagen who has also been compiling some [CSV benchmarks](https://github.com/joelverhagen/NCsvPerf) that you're probably aware of.

**Comment by mgholam** [comment]
Hi Mark,

Why did Johns Hopkins not transform the data (i.e. states as columns and dates as rows which seems more logical)?

In any case the `(o, c)` parameters to the method gives you `c.Count` so you can know how many columns you have, if you add the following code :
```c#
  public struct COLUMNS
  {
...
     // add the following line
     public int Count { get { return _cols.Length; } }
...
  }
```

**Comment by MarkPflug** [comment]
I don't know. Ask JHU?

I don't see a `Count` property on `COLUMNS`. Are you saying I need to add code to your library to do this?  So, there isn't a better way to do this as of 2.0.8?

**Comment by mgholam** [comment]
Yes you need to add the line to the library, until I update it... 

Check back in 5 mins :)

**Comment by MarkPflug** [comment]
Before you do...
Will it still be a problem to know the size of the array in the "Hack" type? Perhaps I can just allocate the array in the binder loop.
nevermind.

**Comment by mgholam** [comment]
With `fastCSV` you do all your processing in the `(o,c)=>{ ... }` method i.e. extract the columns you want and get back a list of the data as a result, if you don't need to return the results but are putting data in another structure outside `fastCSV` just set the data in the anonymous function and `return false` .

**Comment by MarkPflug** [comment]
I'm not sure I understand. Would I need to pass the bind target via closure?

**Comment by mgholam** [comment]
```c#
   // first use case return all the results
   var results = fastCSV.ReadFile(... (o,c)=>{    /* extract columns here */     return true; } ));

   // second use case populate external data
   // externalData
  fastCSV.ReadFile(... (o,c)=>{    externalData.Add( /* columns you want */);    return false; } ));

**Comment by MarkPflug** [comment]
Thanks, that's confirms what I was expecting, requires a captured variable.

Thanks for the `Count` update in  2.0.9. I've updated the [benchmark results](https://github.com/MarkPflug/CsvBenchmarks/blob/main/docs/CsvReaderBenchmarks.md) for 2.0.9 so it doesn't require knowing the column count ahead of time.

**Comment by mgholam** [comment]
👍
