### ISSUE TITLE
How to read all columns

### ISSUE THREAD

**Issue by FreeVB** [mgholam/fastCSV#15]
How to read a file with unknown column name?

Suggestion: add a function to generate datatable directly after reading.

**Comment by mgholam** [comment]
Columns are referenced by an index in the map function i.e. `c[1]`

**Comment by FreeVB** [comment]
I mean, I don't know how many columns there are in the file, and I don't know the column names, for example fastCSV.ReadFile (of localweatherdata) do not use (of localweatherdata)

Finally, the result is generated into datatable, which is used as the source of DataGridView.

**Comment by mgholam** [comment]
`fastCSV` is intended for those times you know what the data is and what you want to do with it in a fast way.

For your case, I would open the file in a text editor first, and figure out what it is.

**Comment by FreeVB** [comment]
OK,
It is suggested that c add a column name attribute, such as C [1]. Colname, so that the column name can be obtained through the c.count loop.

**Comment by FreeVB** [comment]
![aa](https://user-images.githubusercontent.com/30093956/106107234-a90fea00-6181-11eb-9491-b80f42b09f01.png)

The problem is solved! Now there are two problems need to be improved: 1. The column name cannot be read; 2 fastCSV.ReadFile (of localweatherdata) this (of localweatherdata) cannot be cancelled because it is not required to read all unknown columns.

**Comment by mgholam** [comment]
I don't understand your point 2.

**Comment by FreeVB** [comment]
`Dim dt As New DataTable
        Dim list = fastCSV.ReadFile(Of LocalWeatherData)("../../2.txt", True, ","c, Function(o, c)
                                                                                        Dim add As Boolean = True
                                                                                        Dim row As DataRow = dt.NewRow()
                                                                                        For i As Integer = 0 To c.Count - 1
                                                                                            If dt.Columns.Contains("col" & i) = False Then
                                                                                                dt.Columns.Add("col" & i)
                                                                                            End If
                                                                                            row(i) = c(i)
                                                                                        Next i
                                                                                        dt.Rows.Add(row)
                                                                                        line += 1
                                                                                        Return add
                                                                                    End Function)
        DataGridView1.DataSource = dt`

I mean (of localweatherdata) this is not required in the test, but if you delete this, you will get an error. By the way, I use VB.NET It's easy to test.

**Comment by mgholam** [comment]
If you are creating a `DataTable` and not using the return `List` from `fastCSV` then just `return false` in the function.

**Comment by FreeVB** [comment]
Well done! Look forward to column name attribute support! Thank you for your answer, mgholam.

**Comment by FreeVB** [comment]
I have solved all the column names, but it does not seem to be a very good way. I look forward to your better solution.

public static string[] ColName;
private static List<T> ReadData<T>(TextReader sr, bool hasheader, int colcount, char delimiter, ToOBJ<T> mapper)
    {...
ColName = line.ToString().Split(delimiter);
int cc = CountOccurence(line, delimiter);
...}

Demo:
For i As Integer = 0 To c.Count - 1
    If dt.Columns.Contains(fastCSV.ColName(i)) = False Then
        dt.Columns.Add(fastCSV.ColName(i))
    End If
    row(i) = c(i)
Next i

**Comment by mgholam** [comment]
`public static string[] ColName;` is not a good idea with multi-threading.

**Comment by FreeVB** [comment]
You are right and looking forward to your solution.

**Comment by mgholam** [comment]
Sorry for the delay, finally got round to do it, now you can use `c.ColumnName(idx)` in `v2.0.10`

**Comment by FreeVB** [comment]
Hi,mgholam.
I tested your updated method. Although my method is not the best, it is relatively fast. The reading speed of 100000 records can be more than three times faster. Is my test method wrong?
