### ISSUE TITLE
Missing data if hasHeader=false in method fastCSV.ReadFile<>

### ISSUE THREAD

**Issue by schneidgu** [mgholam/fastCSV#4]
Hello,

it seems that  the method fastCSV.ReadFile<T>() will ignore the first data row in CSV file if hasHeader property is set to false.
If the CSV file contains e.g. 5 data rows (without header text row!) you will always retrieve 4 last data objects in CSV file, independent if hasHeader is set tot true or false.

Regards,
Guenter

**Comment by mgholam** [comment]
Should be fixed in `v2.0.3`
