### ISSUE TITLE
Parse from Stream or TextReader?

### ISSUE THREAD

**Issue by joelverhagen** [mgholam/fastCSV#5]
From what I can tell, you can only use `fastCsv.ReadFile` to load CSV data. For my case I am reading CSV data from a network stream (specifically from Azure Blob Storage). I would be nice to have an overload that accepts `StreamReader` or `Stream`.

I'm excited to test the performance of this library along with several others.

I may have time to do a pull request but I figured I'd put the request out there.

**Comment by mgholam** [comment]
Check out `v2.0.4`

**Comment by joelverhagen** [comment]
Great, thanks! Although it feels a bit cumbersome to have to specify the column count.

**edit:** great library by the way. Very promising! Thanks again for the fast response.

**Comment by mgholam** [comment]
You can add the extra overloads, like `ReadFile()`
