### ISSUE TITLE
Extra data left at the end of some records

### ISSUE THREAD

**Issue by joelverhagen** [mgholam/fastCSV#6]
In my usage of your library, I have noticed some records that get deserialized have the last field populated with data from the previous line sometimes. I compared NReco.Csv behavior with your library:

<pre>
Row 2 is different!
NReco.CSV: {
  "ScanId": "7c1985ab-b557-4561-9e3e-7697f25d303a",
  "ScanTimestamp": "2020-11-28T01:50:47.6915182+00:00",
  "Id": "VL.TrackObjects",
  "Version": "0.0.2-alpha",
  "Created": "2020-11-27T22:56:33.19+00:00",
  "ResultType": "NoAssets",
  "PatternSet": "",
  "PropertyAnyValue": "",
  "PropertyCodeLanguage": "",
  "PropertyTargetFrameworkMoniker": "",
  "PropertyLocale": "",
  "PropertyManagedAssembly": "",
  "PropertyMSBuild": "",
  "PropertyRuntimeIdentifier": "",
  "PropertySatelliteAssembly": "",
  "Path": "",
  "FileName": "",
  "FileExtension": "",
  "TopLevelFolder": "",
  "RoundTripTargetFrameworkMoniker": "",
  "FrameworkName": "",
  "FrameworkVersion": "",
  "FrameworkProfile": "",
  "PlatformName": "",
  <b>"PlatformVersion": ""</b>
}
mgholam.fastCSV: {
  "ScanId": "7c1985ab-b557-4561-9e3e-7697f25d303a",
  "ScanTimestamp": "2020-11-28T01:50:47.6915182+00:00",
  "Id": "VL.TrackObjects",
  "Version": "0.0.2-alpha",
  "Created": "2020-11-27T22:56:33.19+00:00",
  "ResultType": "NoAssets",
  "PatternSet": "",
  "PropertyAnyValue": "",
  "PropertyCodeLanguage": "",
  "PropertyTargetFrameworkMoniker": "",
  "PropertyLocale": "",
  "PropertyManagedAssembly": "",
  "PropertyMSBuild": "",
  "PropertyRuntimeIdentifier": "",
  "PropertySatelliteAssembly": "",
  "Path": "",
  "FileName": "",
  "FileExtension": "",
  "TopLevelFolder": "",
  "RoundTripTargetFrameworkMoniker": "",
  "FrameworkName": "",
  "FrameworkVersion": "",
  "FrameworkProfile": "",
  "PlatformName": "",
  <b>"PlatformVersion": "0.0.0.0"</b>
}
</pre>

(see the last property, `PlatformVersion`)

Here is the CSV:
```
c0db9120-80cc-4c0c-9aa7-ccc957348e4f,2020-11-28T01:50:40.5074056+00:00,VIT.COFIDE.GESTIONCUENTAS.Models,1.0.18,2020-11-27T22:42:01.8030000+00:00,AvailableAssets,CompileLibAssemblies,,,netcoreapp3.1,,,,,,lib/netcoreapp3.1/VIT.COFIDE.GESTIONCUENTAS.Models.dll,VIT.COFIDE.GESTIONCUENTAS.Models.dll,.dll,lib,netcoreapp3.1,.NETCoreApp,3.1.0.0,,,0.0.0.0
7c1985ab-b557-4561-9e3e-7697f25d303a,2020-11-28T01:50:47.6915182+00:00,VL.TrackObjects,0.0.2-alpha,2020-11-27T22:56:33.1900000+00:00,NoAssets,,,,,,,,,,,,,,,,,,,
3c219c16-8b8f-4e29-b16c-ed34c5442c73,2020-11-28T01:49:41.7240806+00:00,WOLF.Net,4.0.0-alpha1,2020-11-27T21:19:25.8870000+00:00,AvailableAssets,RuntimeAssemblies,,,netcoreapp3.1,,,,,,lib/netcoreapp3.1/WOLF.Net.dll,WOLF.Net.dll,.dll,lib,netcoreapp3.1,.NETCoreApp,3.1.0.0,,,0.0.0.0
3c219c16-8b8f-4e29-b16c-ed34c5442c73,2020-11-28T01:49:41.7240806+00:00,WOLF.Net,4.0.0-alpha1,2020-11-27T21:19:25.8870000+00:00,AvailableAssets,CompileLibAssemblies,,,netcoreapp3.1,,,,,,lib/netcoreapp3.1/WOLF.Net.dll,WOLF.Net.dll,.dll,lib,netcoreapp3.1,.NETCoreApp,3.1.0.0,,,0.0.0.0
498680e6-31a0-4c27-b79e-d607ef7c8393,2020-11-28T01:49:43.5970660+00:00,WOLF.Net.Redis,3.0.0,2020-11-27T21:20:56.7600000+00:00,AvailableAssets,RuntimeAssemblies,,,netcoreapp3.1,,,,,,lib/netcoreapp3.1/WOLF.Net.Redis.dll,WOLF.Net.Redis.dll,.dll,lib,netcoreapp3.1,.NETCoreApp,3.1.0.0,,,0.0.0.0
498680e6-31a0-4c27-b79e-d607ef7c8393,2020-11-28T01:49:43.5970660+00:00,WOLF.Net.Redis,3.0.0,2020-11-27T21:20:56.7600000+00:00,AvailableAssets,CompileLibAssemblies,,,netcoreapp3.1,,,,,,lib/netcoreapp3.1/WOLF.Net.Redis.dll,WOLF.Net.Redis.dll,.dll,lib,netcoreapp3.1,.NETCoreApp,3.1.0.0,,,0.0.0.0
bd1af124-5907-4227-bf5a-4d3ca5e8ff2e,2020-11-28T01:50:18.4736659+00:00,YPF.MSPromotions.DTO,1.0.4.24,2020-11-27T21:50:20.3230000+00:00,AvailableAssets,RuntimeAssemblies,,,netcoreapp2.2,,,,,,lib/netcoreapp2.2/YPF.MSPromotions.DTO.dll,YPF.MSPromotions.DTO.dll,.dll,lib,netcoreapp2.2,.NETCoreApp,2.2.0.0,,,0.0.0.0
bd1af124-5907-4227-bf5a-4d3ca5e8ff2e,2020-11-28T01:50:18.4736659+00:00,YPF.MSPromotions.DTO,1.0.4.24,2020-11-27T21:50:20.3230000+00:00,AvailableAssets,CompileLibAssemblies,,,netcoreapp2.2,,,,,,lib/netcoreapp2.2/YPF.MSPromotions.DTO.dll,YPF.MSPromotions.DTO.dll,.dll,lib,netcoreapp2.2,.NETCoreApp,2.2.0.0,,,0.0.0.0
02870803-36bd-4ae5-acd5-3b89e6bbdc70,2020-11-28T01:45:51.1358087+00:00,YPF.MSPromotions.DTO,1.0.4.24-beta,2020-11-27T19:55:12.1870000+00:00,AvailableAssets,RuntimeAssemblies,,,netcoreapp2.2,,,,,,lib/netcoreapp2.2/YPF.MSPromotions.DTO.dll,YPF.MSPromotions.DTO.dll,.dll,lib,netcoreapp2.2,.NETCoreApp,2.2.0.0,,,0.0.0.0
02870803-36bd-4ae5-acd5-3b89e6bbdc70,2020-11-28T01:45:51.1358087+00:00,YPF.MSPromotions.DTO,1.0.4.24-beta,2020-11-27T19:55:12.1870000+00:00,AvailableAssets,CompileLibAssemblies,,,netcoreapp2.2,,,,,,lib/netcoreapp2.2/YPF.MSPromotions.DTO.dll,YPF.MSPromotions.DTO.dll,.dll,lib,netcoreapp2.2,.NETCoreApp,2.2.0.0,,,0.0.0.0
```

Here is a repro: [CsvRepro.zip](https://github.com/mgholam/fastCSV/files/5612625/CsvRepro.zip)

**Comment by mgholam** [comment]
`ParseLine()` is reusing the `cols`  structure and it is not being zeroed (it assumes there is new data)

**Comment by joelverhagen** [comment]
Is this a bug? Or should code using a library zero out the structure somehow?

**Comment by mgholam** [comment]
bug/performance feature

**Comment by joelverhagen** [comment]
It seems to only happen on the last field of a row.

So this messes up:
```
a,b,c
d,e,
f,g,h
```

But this does not:
```
a,b,c
d,,e
f,g,h
```

**Comment by mgholam** [comment]
Checkout `v2.0.5`

**Comment by schneidgu** [comment]
This is still not fixed completely in v2.0.5.

E.g. you have a tab seperated CSV file with 2 columns and the last row just contains a tab char.

In this case the object for last row contains data of previous row.

To fix this I used the following code addition for method ParseLine():

    private unsafe static COLUMNS.MGSpan[] ParseLine(COLUMNS.MGSpan line, char delimiter, COLUMNS.MGSpan[] columns)
    {
        // because columns array is reused --> take care that previous row data is really ignored !!
        for (int i = 0; i < columns.Length; i++)
        {
            columns[i].Start = 0;
            columns[i].Count = 0;
        }

       ........
   }

Regards,
Guenter

**Comment by mgholam** [comment]
Hopefully it should be fixed!

**Comment by schneidgu** [comment]
Still not fixed in v2.0.6. Here is a UnitTest illustrating the problem:

```

using Microsoft.VisualStudio.TestTools.UnitTesting;
using System.Diagnostics;
using System.IO;

namespace MyUtilsTests.parser
{
    [TestClass]
    public class UnitTest_FastCSV
    {
        [TestMethod]
        public void Test_CSV()
        {
            string data = "11,12,13\r\n21,22,23\r\n31,,33\r\n41,42,43\r\n,52,";
            string result = DoParsing(data);
            Assert.AreEqual(data, result);

            data = "11,12,13\r\n21,22,23\r\n31,,33\r\n41,42,43\r\n,,";
            result = DoParsing(data);
            Assert.AreEqual(data, result);

            data = "11,12,13\r\n21,22,23\r\n31,,\r\n41,42,43\r\n,,";
            result = DoParsing(data);
            Assert.AreEqual(data, result);
        }


        private string DoParsing(string csvContent)
        {
            string r = "";

            using (var tr = new StringReader(csvContent))
            {
                var li = fastCSV.ReadStream<ABC>(
                tr,
                false,
                ',',
                (o, c) =>
                {
                    o.a = c[0];
                    o.b = c[1];
                    o.c = c[2];
                    return true;
                });

                foreach (ABC c in li)
                {
                    if (r.Length > 0)
                    {
                        r = r + "\r\n" + c.ToString();
                    }
                    else
                    {
                        r = c.ToString();
                    }
                }
            }
            return r;
        }


        [DebuggerDisplay("A = {a}; B = {b}; C = {c}")]
        public class ABC
        {
            public string a { get; set; }
            public string b { get; set; }
            public string c { get; set; }

            public new string ToString()
            {
                return a + "," + b + "," + c;
            }
        }
    }
}
```


Using my proposed solution the unit test passes

**Comment by mgholam** [comment]
Checkout `v2.0.7`

**Comment by joelverhagen** [comment]
Works for me!

**Comment by mgholam** [comment]
Woo Hoo!!
