### ISSUE TITLE
Close TextReader in method ReadData<T>()

### ISSUE THREAD

**Issue by schneidgu** [mgholam/fastCSV#9]
The TextReader in method ReadData<T>() must be closed, otherwise the CSV file is blocked (e.g. can't be renamed)

E.g.:

    private static List<T> ReadData<T>(TextReader tr, bool hasheader, int colcount, char delimiter, ToOBJ<T> mapper)
    {
        try
        {
           .....
        }
        finally
        {
            tr.Close();
        }
    }

(use using statements ...)

**Comment by mgholam** [comment]
Moved the `Close()` inside the exception otherwise it would happen after the first line is read.
